version: '3.8'

services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api

  api:
    build: 
      context: ./backend
    ports:
      - 8080:8080
    env_file:
      - ./backend/db.env
      - ./backend/admin.env
      - ./backend/JWT.env
    depends_on:
      - database
    entrypoint: ["/wait-for-it.sh", "database:3306", "--", "java", "-jar", "/app/app.jar"]

  database:
    image: mysql:8.0  
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - web
      - api
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf # Nginx 설정 파일
      - ./frontend/build:/usr/share/nginx/html # React의 정적 파일 디렉토리 매핑